services:
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      proxy:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ../:/var/www
      - ./conf/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - proxy
    depends_on:
      - api
      - client
  api:
    build:
      context: backend
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/code
    environment:
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: mongodb://root:example@mongo:27017/
      HANDSFREE_SETTINGS: 'secret_config.py'
    networks:
      proxy:
    depends_on:
        - redis
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3008:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://api:4000
    depends_on:
      - api
    networks:
      proxy:
networks:
  proxy:
